### ISSUE TITLE
io decoder error

### ISSUE THREAD

**Issue by ErdanThren** [IamRyan30/Decursio-Team#4]
when trying to launch getting the following error message:

internal exception: io.netty.handler.codec.decoderexception java.lang.nullpointerexception

this is on internal and network server

**Comment by ErdanThren** [comment]
[23:06:40] [main/FATAL]: Error executing task on Client
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraftforge.network.NetworkFilters.lambda$injectIfNecessary$1(NetworkFilters.java:48) ~[?:?]
	at net.minecraftforge.network.NetworkFilters$$Lambda$33914/476985387.accept(Unknown Source) ~[?:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:146) ~[guava-21.0.jar:?]
	at net.minecraftforge.network.NetworkFilters.injectIfNecessary(NetworkFilters.java:44) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.sendMCRegistryPackets(NetworkHooks.java:121) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147282_a(ClientPlayNetHandler.java:399) ~[?:?]
	at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:110) ~[?:?]
	at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:18) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$33687/1217718769.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$496/104803851.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[23:06:40] [main/INFO]: Client cache cleared!
[23:06:40] [Sound engine/ERROR]: Failed to read from audio stream
java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202) ~[?:1.8.0_51]
	at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:292) ~[?:1.8.0_51]
	at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:49) ~[?:1.8.0_51]
	at com.sun.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:1491) ~[zipfs.jar:1.8.0_51]
	at com.sun.nio.zipfs.ZipFileSystem$5.fill(ZipFileSystem.java:1430) ~[zipfs.jar:1.8.0_51]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_51]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_51]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_51]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_51]
	at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[?:1.8.0_51]
	at java.io.FilterInputStream.read(FilterInputStream.java:107) ~[?:1.8.0_51]
	at net.minecraft.client.audio.OggAudioStream.func_216456_c(SourceFile:113) ~[?:?]
	at net.minecraft.client.audio.OggAudioStream.func_216460_a(SourceFile:160) ~[?:?]
	at net.minecraft.client.audio.OggAudioStream.func_216455_a(SourceFile:224) ~[?:?]
	at net.minecraft.client.audio.OggAudioStreamWrapper.func_216455_a(SourceFile:41) ~[?:?]
	at net.minecraft.client.audio.SoundSource.func_216421_a(SourceFile:151) [?:?]
	at net.minecraft.client.audio.SoundSource.func_216433_a(SourceFile:140) [?:?]
	at net.minecraft.client.audio.SoundEngine.lambda$null$7(SoundEngine.java:349) [?:?]
	at net.minecraft.client.audio.SoundEngine$$Lambda$32781/787657964.accept(Unknown Source) [?:?]
	at net.minecraft.client.audio.ChannelManager$Entry.func_217890_b(SourceFile:34) [?:?]
	at net.minecraft.client.audio.ChannelManager$Entry$$Lambda$32706/2036948577.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.client.audio.SoundEngineExecutor.func_213178_c(SourceFile:42) [?:?]
	at net.minecraft.client.audio.SoundEngineExecutor$$Lambda$24429/3864668.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[23:06:40] [main/INFO]: Removed all colony views

**Comment by IamRyan30** [comment]
I need more info to help you with this problem. This is not even a full log. Is there a crash file for this? Complete our issue template properly.
